import { UPGRADES, upgradeCost, upgradePrerequisites, upgradeRequirement, machineRequirement, machinePrice, blocked, dailyObligations, type State, type Upgrade } from './engine';
import './tree.css';
const rp = (n: number) => `Rp${n.toLocaleString('id-ID')}`;
const icons: Record<Upgrade, number> = { stamina: 0, efficient: 5, luck: 1, payout: 2, hold: 3, turbo: 5, auto: 3, fare: 4, orders: 2, safety: 5 };
function node(s: State, id: Upgrade) {
 const u=UPGRADES[id], rank=s.upgrades[id], max=rank===u.max, ready=upgradePrerequisites(s,id), price=upgradeCost(s,id);
 return `<button class="tree-node ${rank?'owned':''} ${!ready?'locked':''} ${ready&&!max&&s.cash<price?'unaffordable':''}" data-upgrade="${id}" ${blocked(s)||max||!ready||s.cash<price?'disabled':''} aria-label="${u.name}, rank ${rank} dari ${u.max}. ${u.desc}. ${!ready?'Perlu '+upgradeRequirement(id):max?'Maksimal':rp(price)}"><span class="tree-medallion tree-art-${icons[id]}"></span><span class="tree-node-name">${u.name}</span><span class="tree-ranks" aria-hidden="true">${Array.from({length:u.max},(_,i)=>`<i class="${i<rank?'filled':''}"></i>`).join('')}</span><small>${u.desc}</small><b>${!ready?'Perlu '+upgradeRequirement(id):max?'✓ MAKSIMAL':s.cash<price?'Kurang '+rp(price-s.cash):rp(price)}</b></button>`;
}
function machine(s: State,id:1|2) {
 const owned=id===1?s.sultanUnlocked:s.cascadeUnlocked, requirement=machineRequirement(s,id), price=machinePrice(id);
 return `<button class="tree-node tree-machine ${owned?'owned':''} ${requirement&&!owned?'locked':''}" data-tree-machine="${id}" ${blocked(s)||owned||!!requirement||s.cash<price?'disabled':''}><span class="tree-medallion tree-art-3"></span><span class="tree-node-name">${id===1?'Sultan Malam':'Rantai Rejeki'}</span><span class="tree-ranks"><i class="${owned?'filled':''}"></i></span><small>${id===1?'Buka 3 jalur. Pasangan & tripel membayar.':'Buka cascade. Tripel runtuh, pengali 1× → 2× → 4×.'}</small><b>${owned?'✓ MESIN TERBUKA':requirement?'Perlu '+requirement:rp(price)}</b></button>`;
}
export function renderTree(s: State, branch = 'all'): string {
 return `<div class="progression-tree" data-branch="${branch}"><div class="tree-intro"><span>RENCANA BESOK</span><h3>Satu langkah lebih jauh.</h3><p>Pilih cabangmu. Beli node sebelumnya untuk membuka yang berikutnya; setiap titik adalah satu rank.</p></div><div class="tree-wallet"><span>Saldo tersedia<strong>${rp(s.cash)}</strong></span><span>Tagihan hari ini<strong>${rp(dailyObligations(s))}</strong></span></div><nav class="tree-filters" aria-label="Cabang upgrade">${[['all','Semua'],['general','Keseharian'],['slots','Mesin'],['ojol','Di Jalan']].map(([id,label])=>`<button data-story="tree-filter" data-branch="${id}" aria-pressed="${branch===id}">${label}</button>`).join('')}</nav><div class="tree-branches"><section class="tree-branch general"><header><span>01</span><h4>KESEHARIAN</h4><p>Lebih banyak ruang gerak.</p></header>${node(s,'stamina')}${node(s,'efficient')}${node(s,'luck')}</section><section class="tree-branch slots"><header><span>02</span><h4>MESIN</h4><p>Pengali & cara bermain baru.</p></header>${node(s,'payout')}<div class="tree-fork">${node(s,'hold')}${node(s,'turbo')}</div><div class="tree-fork">${node(s,'auto')}${machine(s,1)}</div>${machine(s,2)}</section><section class="tree-branch ojol"><header><span>03</span><h4>DI JALAN</h4><p>Kerja yang lebih produktif.</p></header>${node(s,'fare')}${node(s,'orders')}${node(s,'safety')}</section></div><p class="tree-footnote">Upgrade dibayar dari saldo. Sisakan biaya hidup dan pembayaran utang.</p></div>`;
}
